const facts = [
    "A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.",
    "A cat has 230 bones in its body. A human has 206. A cat has no collarbone, so it can fit through any opening the size of its head.",
    "A cat has approximately 60 to 80 million olfactory cells (a human has between 5 and 20 million).",
    "A cat has more bones than a human being; humans have 206 and the cat has 230 bones.",
    "A cat has two vocal chords, and can make over 100 sounds.",
    "A cat lover is called an Ailurophilia (Greek: cat+lover).",
    "A cat will tremble or shiver when it is in extreme pain.",
    "A cat's appetite is the barometer of its health. Any cat that does not eat or drink for more than two days should be taken to a vet.",
    "A cat's brain is more similar to a man's brain than that of a dog.",
    "A cat's field of vision is about 200 degrees.",
    "A cat's hearing is much more sensitive than humans and dogs.",
    "A cat's jaw has only up and down motion; it does not have any lateral, side to side motion, like dogs and humans.",
    "A cat's normal temperature varies around 101 F // 38 C.",
    "A cat's whiskers are thought to be a kind of radar, which helps a cat gauge the space it intends to walk through.",
    "A cats field of vision is about 185 degrees.",
    "Cats eat grass to aid their digestion and to help them get rid of any fur in their stomachs.",
    "Cats have \"nine lives\" thanks to a flexible spine and powerful leg and back muscles.",
    "Cats have 30 vertebrae (humans have 33 vertebrae during early development; 26 after the sacral and coccygeal regions fuse).",
    "Cats have 300 million neurons; dogs have about 160 million.",
    "Cats have about 130,000 hairs per square inch (20,155 hairs per square centimeter).",
    "Cats have been domesticated for half as long as dogs have been.",
    "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
    "Cats have supersonic hearing.",
    "Cats have the largest eyes of any mammal.",
    "Cats lap liquid from the underside of their tongue, not from the top.",
    "Cats lived with soldiers in trenches, where they killed mice during World War I.",
    "Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.",
    "Cats make about 100 different sounds. Dogs make only about 10.",
    "Cats must have fat in their diet because they can't produce it on their own.",
    "Cats often overract to unexpected stimuli because of their extremely sensitive nervous system.",
    "Cats purr at the same frequency as an idling diesel engine, about 26 cycles per second.",
    "Cats respond better to women than to men, probably due to the fact that women's voices have a higher pitch.",
    "Cats respond most readily to names that end in an \"ee\" sound.",
    "Cats see six times better in the dark and at night than humans.",
    "Cats sleep 16 to 18 hours per day. When cats are asleep, they are still alert to incoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.",
    "Cats spend nearly 1/3 of their waking hours cleaning themselves.",
    "Cats step with both left legs, then both right legs when they walk or run.",
    "Cats take between 20-40 breaths per minute.",
    "Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do thismore often, especially when they are excited.",
    "Cats walk on their toes.",
    "Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.",
    "In relation to their body size, cats have the largest eyes of any mammal.",
    "In the 1750s, Europeans introduced cats into the Americas to control pests.",
    "In the largest cat breed, the average male weighs approximately 20 pounds.",
    "In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.",
    "It has been scientifically proven that owning cats is good for our health and can decrease the occurrence of high blood pressure and other illnesses.",
    "It has been scientifically proven that stroking a cat can lower one's blood pressure.",
    "It may take as long as 2 weeks for a kitten to be able to hear well.  Their eyes usually open between 7 and 10 days, but sometimes it happens in as little as 2 days.",
    "Jaguars are the only big cats that don't roar.",
    "Julius Ceasar, Henri II, Charles XI, and Napoleon were all afraid of cats.",
    "Kittens remain with their mother till the age of 9 weeks.",
    "Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.",
    "Unlike humans, cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.",
    "Unlike other cats, lions have a tuft of hair at the end of their tails.",
    "When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.",
    "When a cat drinks, its tongue - which has tiny barbs on it - scoops the liquid up backwards.",
    "When a cats rubs up against you, the cat is marking you with it's scent claiming ownership.",
    "When a domestic cat goes after mice, about 1 pounce in 3 results in a catch.",
    "While many parts of Europe and North America consider the black cat a sign of bad luck, in Britain and Australia black cats are considered lucky.",
    "You check your cats pulse on the inside of the back thigh, where the leg joins to the body.",
    "In 1987 cats overtook dogs as the number one pet in America.",
    "Auxim's cat Lotje is not only lazy, but also incredibly lazy."
];

module.exports = facts;